POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "adam_richard",
  "name": "Adam Richard",
  "password": "richard_567",
  "gender": "male",
  "location": "Detroit"
}
###

GET http://localhost:3000/
###

POST http://localhost:3000/addData
Content-Type: application/json

{
  "imageUrl":"https://res.cloudinary.com/dwoqcvsxt/image/upload/v1697094884/art6_uawder.png"
}
###


POST http://localhost:3000/login
Content-Type: application/json

{
    "username":"adam_richard",
    "password":"richard_567"
}
###

DELETE http://localhost:3000/drop